### ISSUE TITLE
Pls update for Forge, 1.20.1 and upload to CurseForge

### ISSUE THREAD

**Issue by Haemschter** [wefcdse/fpv20#1]
Pls update for Forge, 1.20.1 and upload to CurseForge.

Woud be nice if you have any videos about the mod here.

**Comment by wefcdse** [comment]
There is a video, but it's on bilibili and it's in Chinese though. I will make another soon.
https://www.bilibili.com/video/BV1ep421Z7KK
Sorry I don't know how to make mod in forge, that's also why I made a new mod rather than port Minecraft fpv.
However, there is a mod that let fabric mod run in forge, you can try that mod(but I don't know the name of it though)
The mod is in early develoment, and I'm going to upload it to CurseForge in a few days. You can just download it in github action now.

**Comment by wefcdse** [comment]
I tryed to use this mod in Sinytra Connector, but it didnot behave correctly, I don't know if I can fix it since I know nearly nothing about forge modding.

**Comment by wefcdse** [comment]
> Pls update for Forge, 1.20.1 and upload to CurseForge.
> 
> Woud be nice if you have any videos about the mod here.

now this mod can run in forge with Sinytra Connector
